// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/agent/traffic.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TrafficServiceClient is the client API for TrafficService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrafficServiceClient interface {
	CreateTrafficCounter(ctx context.Context, in *CreateTrafficCounterRequest, opts ...grpc.CallOption) (*CreateTrafficCounterResponse, error)
	DumpTrafficReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (TrafficService_DumpTrafficReportClient, error)
}

type trafficServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficServiceClient(cc grpc.ClientConnInterface) TrafficServiceClient {
	return &trafficServiceClient{cc}
}

func (c *trafficServiceClient) CreateTrafficCounter(ctx context.Context, in *CreateTrafficCounterRequest, opts ...grpc.CallOption) (*CreateTrafficCounterResponse, error) {
	out := new(CreateTrafficCounterResponse)
	err := c.cc.Invoke(ctx, "/proto.TrafficService/CreateTrafficCounter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trafficServiceClient) DumpTrafficReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (TrafficService_DumpTrafficReportClient, error) {
	stream, err := c.cc.NewStream(ctx, &TrafficService_ServiceDesc.Streams[0], "/proto.TrafficService/DumpTrafficReport", opts...)
	if err != nil {
		return nil, err
	}
	x := &trafficServiceDumpTrafficReportClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TrafficService_DumpTrafficReportClient interface {
	Recv() (*DumpTrafficReportResponse, error)
	grpc.ClientStream
}

type trafficServiceDumpTrafficReportClient struct {
	grpc.ClientStream
}

func (x *trafficServiceDumpTrafficReportClient) Recv() (*DumpTrafficReportResponse, error) {
	m := new(DumpTrafficReportResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TrafficServiceServer is the server API for TrafficService service.
// All implementations must embed UnimplementedTrafficServiceServer
// for forward compatibility
type TrafficServiceServer interface {
	CreateTrafficCounter(context.Context, *CreateTrafficCounterRequest) (*CreateTrafficCounterResponse, error)
	DumpTrafficReport(*Empty, TrafficService_DumpTrafficReportServer) error
	mustEmbedUnimplementedTrafficServiceServer()
}

// UnimplementedTrafficServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTrafficServiceServer struct {
}

func (UnimplementedTrafficServiceServer) CreateTrafficCounter(context.Context, *CreateTrafficCounterRequest) (*CreateTrafficCounterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrafficCounter not implemented")
}
func (UnimplementedTrafficServiceServer) DumpTrafficReport(*Empty, TrafficService_DumpTrafficReportServer) error {
	return status.Errorf(codes.Unimplemented, "method DumpTrafficReport not implemented")
}
func (UnimplementedTrafficServiceServer) mustEmbedUnimplementedTrafficServiceServer() {}

// UnsafeTrafficServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficServiceServer will
// result in compilation errors.
type UnsafeTrafficServiceServer interface {
	mustEmbedUnimplementedTrafficServiceServer()
}

func RegisterTrafficServiceServer(s grpc.ServiceRegistrar, srv TrafficServiceServer) {
	s.RegisterService(&TrafficService_ServiceDesc, srv)
}

func _TrafficService_CreateTrafficCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTrafficCounterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficServiceServer).CreateTrafficCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TrafficService/CreateTrafficCounter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficServiceServer).CreateTrafficCounter(ctx, req.(*CreateTrafficCounterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrafficService_DumpTrafficReport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrafficServiceServer).DumpTrafficReport(m, &trafficServiceDumpTrafficReportServer{stream})
}

type TrafficService_DumpTrafficReportServer interface {
	Send(*DumpTrafficReportResponse) error
	grpc.ServerStream
}

type trafficServiceDumpTrafficReportServer struct {
	grpc.ServerStream
}

func (x *trafficServiceDumpTrafficReportServer) Send(m *DumpTrafficReportResponse) error {
	return x.ServerStream.SendMsg(m)
}

// TrafficService_ServiceDesc is the grpc.ServiceDesc for TrafficService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrafficService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TrafficService",
	HandlerType: (*TrafficServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrafficCounter",
			Handler:    _TrafficService_CreateTrafficCounter_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DumpTrafficReport",
			Handler:       _TrafficService_DumpTrafficReport_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/agent/traffic.proto",
}
